/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'message' : IDL.Opt(IDL.Text),
  'preferredDate' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'eventType' : IDL.Text,
});

export const idlService = IDL.Service({
  'deleteBooking' : IDL.Func([IDL.Nat], [], []),
  'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
  'listAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'submitBooking' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Int,
      ],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'message' : IDL.Opt(IDL.Text),
    'preferredDate' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'eventType' : IDL.Text,
  });
  
  return IDL.Service({
    'deleteBooking' : IDL.Func([IDL.Nat], [], []),
    'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
    'listAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'submitBooking' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Int,
        ],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };